### ISSUE TITLE
Error thrown in with usage of string in closure

### ISSUE THREAD

**Issue by bswatson** [nexcess/limit-orders#16]
https://github.com/nexcess/limit-orders/blob/bd3acb9e12d47d4d42b492c4983014bdeba77321/limit-orders.php#L24

[20-Apr-2020 15:51:12 UTC] PHP Catchable fatal error:  Argument 1 passed to WP_CLI\Runner::Nexcess\LimitOrders\{closure}() must be an instance of Nexcess\LimitOrders\string, string given in /chroot/home/aa5b74b2/ssldelay.watsonbot.com/html/wp-content/plugins/limit-orders/limit-orders.php on line 24

**Comment by stevegrunwell** [comment]
Lemme guess, PHP 7.1 or older 🤦

**Comment by bswatson** [comment]
That is correct. Seeing this issue on at least 7.3 and 7.4.

**Comment by bswatson** [comment]
Actually, seeing this in PHP 7.0 as well.

**Comment by stevegrunwell** [comment]
Hmm, perhaps this isn't as simple as I had thought; [PHP added typehint support for the `string` scalar type back in PHP 7.0.0](https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types), so this shouldn't be a matter of PHP interpreting the "string" typehint as a class name.

Our autoloader also follows [the FIG example of a PSR-4 autoloader](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md#closure-example) pretty closely (though they forego typehinting). I'll rework the autoloader to explicitly cast to string rather than typehint, but could you please post a list of other plugins running in case there's a conflict with another autoloader?

**Comment by bswatson** [comment]
I have only been able to replicate this when trying to install a plugin through the Nexcess Dashboard Installer.

**Comment by stevegrunwell** [comment]
Once 1.2.0 is tagged, let's make sure to retest this; everything in the codebase should be PHP 7.0+ compliant, so this may be a problem in the dashboard installer.

**Comment by stevegrunwell** [comment]
Closing this, as we were able to sort out the issue (resolved in version 1.2.1 of the Nexcess Installer plugin).
