### ISSUE TITLE
Exclude a product 

### ISSUE THREAD

**Issue by Camilo517** [nexcess/limit-orders#40]
Hello, a client asks me to exclude a product from this limitation
I think it is necessary, especially if a user publishes a special product or on sale that they want to sell quickly.
An example of how this could be done
![Screenshot_10](https://user-images.githubusercontent.com/43606394/85961539-639cfb80-b9ab-11ea-8695-b7a0a931e042.png)

https://wordpress.org/support/topic/exclude-a-product/
Good plugin and very good idea :)

**Comment by stevegrunwell** [comment]
The plugin works based on the total number of orders within an interval, and is designed to help store owners who are overwhelmed with an influx of orders (for example, a store owner for whom inventory is no issue but they can physically only package 50 orders in a day).

Since it's based on **total** orders, the logic around "turning off" the store is pretty simple: [4 callbacks defined in `OrderLimiter::disable_ordering()`](https://github.com/nexcess/limit-orders/blob/develop/src/OrderLimiter.php#L298). You could write logic to conditionally unhook these callbacks based on your client's business logic, but it seems like the plugin might not be compatible with what you're trying to accomplish.

Furthermore, excluding certain items from the limits raises a lot of questions around what should — or should **not** — count against the limit: do orders that contain the excluded item(s) _ever_ count against the limit? Are orders permitted after the limit has been reached if they only contain the excluded item(s)? What if they include the excluded item(s) _plus_ other items?

## Example 

Let's imagine we have a pet supply store, selling three types of pet food: dog food, cat food, and fish food. Due to labor shortages, we can only handle preparing 100 orders a day for shipment. We decide to **exclude fish food** from order limiting.

Under which of the following scenarios should the store accept the 101st order?

1. We've received 50 orders for just dog food, and 50 for just cat food. Someone wishes to make an order for fish food.
2. Same as above, but the 101st order is for fish food *and* cat food.
3. We've received 50 orders for dog food and 50 orders for fish food. Now, someone wants to order cat food.
4. We've received 100 orders for just fish food. Now, someone wishes to order dog food.
5. Same as 4, but they wish to order dog food *and* fish food
6. 75 orders of dog food, 25 orders of cat **and** fish food. 101st order is for _just_ cat food.

| Scenario # | First 100 orders | 101st order | Should order be accepted? |
| --- | --- | --- | --- |
| 1 | 50 x 🐶 + 50 x 🐱 | 🐟 | ? |
| 2 | 50 x 🐶 + 50 x 🐱 | 🐟 + 🐱 | ? |
| 3 | 50 x 🐶 + 50 x 🐟 | 🐱 | ? |
| 4 | 100 x 🐟 | 🐶 | ? |
| 5 | 100 x 🐟 | 🐶 + 🐟 | ? |
| 6 | 75 x 🐶 + 25 x (🐱+ 🐟) | 🐱 | ? |

An **order** is made up of one or more **products**, so this really comes down to classification: what counts, and what doesn't? This classification becomes even more complicated if multiple products are marked as excluded; if we added bird seed into our pet food matrix as an excluded item, the matrix would continue to grow.

Adding a method to exclude products from the limiter would require considering each of these scenarios, which is adding undue complexity for the majority of stores running this plugin. If there are filters that would be helpful to enable you to inject your custom business logic we'd be more than happy to consider adding them, but I don't foresee us adding excluded products at this time.

Thank you for the suggestion, and best of luck!

**Comment by Camilo517** [comment]
Hello @stevegrunwell Thanks for responding and for your time :)
The store limited to 100 daily orders. The product with id 38 is excluded from this limitation, its limit goes by stock
Thanks
